In [27]:
from pathlib import Path

import pandas as pd

from source.utils.sample import sample_pickle as sp
from source.utils.associate import AM_DF_DIR, adjust_assoc_columns
from source.utils import POST_PROC_DIR
FOCUS_ORIG = ['f', 'E11', 'unexpected_f', 'unexpected_abs_sqrt',
         'am_p1_given2', 'conservative_log_ratio',
         'am_log_likelihood', 't_score',
         'mutual_information', 'am_odds_ratio_disc',
         'N', 'f1', 'f2', 'l1', 'l2']
FOCUS = adjust_assoc_columns(FOCUS_ORIG)
HITS_PATH = POST_PROC_DIR.joinpath('RBXadj/bigrams_frq-thr0-001p.10f.pkl.gz')
pd.set_option("display.float_format", '{:,.2f}'.format)
pd.set_option("display.max_colwidth", 80)
adv_am = pd.read_csv(AM_DF_DIR / 'Top8NEG-ADV_combined.35f-7c_2024-05-11.csv').set_index('adv')
adv_am

,G2_MIR,G2_SET,LRC_MIR,LRC_SET,MI_MIR,MI_SET,N_MIR,N_SET,...,odds_r_disc_MIR,odds_r_disc_SET,t_MIR,t_SET,unexp_abs_sqrt_MIR,unexp_abs_sqrt_SET,unexp_f_MIR,unexp_f_SET
adv,,,,,,,,,,,,,,,,,
necessarily,"1,688.91","219,003.46",2.66,6.23,0.60,1.30,2032082,"86,330,752.00",...,0.91,1.90,23.36,196.41,26.98,201.47,727.82,"40,589.32"
exactly,"1,939.47","214,404.20",3.51,5.90,0.70,1.28,2032082,"86,330,752.00",...,1.20,1.80,22.86,197.87,25.53,203.31,651.85,"41,333.02"
that,"7,632.21","781,016.11",2.86,5.62,0.60,1.25,2032082,"86,330,752.00",...,0.92,1.72,49.45,383.70,57.07,395.04,"3,257.09","156,053.76"
immediately,181.20,"239,462.58",0.79,4.96,0.29,1.17,2032082,"86,330,752.00",...,0.37,1.52,9.83,223.31,14.09,231.22,198.40,"53,463.24"
yet,242.23,"209,055.78",1.18,4.74,0.39,1.14,2032082,"86,330,752.00",...,0.51,1.45,10.54,212.65,13.73,220.78,188.50,"48,745.17"
terribly,847.65,"42,704.93",1.14,3.09,0.32,0.84,2032082,"86,330,752.00",...,0.41,0.95,20.74,114.85,28.71,124.22,824.16,"15,431.57"
remotely,"4,009.84","13,354.33",3.35,3.03,0.67,0.84,2032082,"86,330,752.00",...,1.10,0.95,33.82,64.35,38.12,69.64,"1,452.96","4,849.60"
only,-716.03,"261,936.36",-1.73,3.04,-0.64,0.82,2032082,"86,330,752.00",...,-0.69,0.94,-43.70,286.38,23.97,311.00,-574.75,"96,723.87"
before,"1,080.52","1,062.13",5.11,3.65,0.83,1.05,2032082,"86,330,752.00",...,2.58,1.26,14.53,16.05,15.73,16.82,247.47,283.05
ever,"15,340.34",353.58,5.57,0.28,0.80,0.11,2032082,"86,330,752.00",...,1.79,0.11,57.78,16.97,63.00,36.21,"3,968.80","1,310.95"
any,"2,511.26","23,683.00",3.48,2.28,0.69,0.64,2032082,"86,330,752.00",...,1.17,0.71,26.24,96.20,29.38,109.42,862.98,"11,973.50"
particularly,"17,999.07","40,303.42",3.15,1.43,0.63,0.41,2032082,"86,330,752.00",...,1.00,0.45,73.86,145.10,84.35,185.14,"7,114.74","34,275.16"

In [2]:
adv_set = set(adv_am.index.to_list())
adv_set

{'any',
 'before',
 'ever',
 'exactly',
 'immediately',
 'necessarily',
 'only',
 'particularly',
 'remotely',
 'terribly',
 'that',
 'yet'}

In [28]:
adv_adj_am = adjust_assoc_columns(
    pd.read_pickle(AM_DF_DIR.joinpath('adv_adj/RBXadj/extra/AdvAdj_frq-thrMIN-7.35f_min200x_extra.pkl.gz'))
                                  ).filter(items=FOCUS).sort_values('LRC', ascending = False)
adv_adj_am = adv_adj_am.loc[adv_adj_am.l1.isin(adv_set), :]
adv_adj_am

,f,exp_f,unexp_f,unexp_abs_sqrt,dP1,LRC,G2,t,MI,odds_r_disc,N,f1,f2,l1,l2
key,,,,,,,,,,,,,,,
yet~unborn,463,0.75,462.25,21.50,0.73,10.47,"5,505.48",21.48,2.79,3.36,86330753,101707,635,yet,unborn
only~half-joking,209,1.17,207.83,14.42,0.96,9.48,"2,116.01",14.38,2.25,3.66,86330753,464174,217,only,half-joking
immediately~accretive,243,0.68,242.32,15.57,0.43,8.65,"2,499.70",15.55,2.56,2.80,86330753,103177,565,immediately,accretive
exactly~alike,3040,9.46,"3,030.54",55.05,0.23,8.55,"29,939.32",54.96,2.51,2.64,86330753,61599,13261,exactly,alike
yet~unnamed,771,2.62,768.38,27.72,0.35,8.47,"7,535.14",27.67,2.47,2.66,86330753,101707,2227,yet,unnamed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
only~high,327,"3,177.51","-2,850.51",53.39,-0.00,-2.86,"-4,245.38",-157.63,-0.99,-0.99,86330753,464174,590978,only,high
only~sure,339,"4,543.20","-4,204.20",64.84,-0.01,-3.34,"-6,708.28",-228.34,-1.13,-1.13,86330753,464174,844981,only,sure
ever~many,206,"3,193.77","-2,987.77",54.66,-0.00,-3.42,"-4,923.30",-208.17,-1.19,-1.20,86330753,124592,2212989,ever,many
particularly~different,349,"6,070.21","-5,721.21",75.64,-0.01,-3.72,"-9,542.66",-306.25,-1.24,-1.25,86330753,575961,909864,particularly,different
only~many,480,"11,898.56","-11,418.56",106.86,-0.01,-4.29,"-20,101.74",-521.18,-1.39,-1.41,86330753,464174,2212989,only,many

In [29]:
adv = 'exactly'
adv_am.loc[['exactly'], :]

,G2_MIR,G2_SET,LRC_MIR,LRC_SET,MI_MIR,MI_SET,N_MIR,N_SET,...,odds_r_disc_MIR,odds_r_disc_SET,t_MIR,t_SET,unexp_abs_sqrt_MIR,unexp_abs_sqrt_SET,unexp_f_MIR,unexp_f_SET
adv,,,,,,,,,,,,,,,,,
exactly,"1,939.47","214,404.20",3.51,5.90,0.70,1.28,2032082,"86,330,752.00",...,1.20,1.80,22.86,197.87,25.53,203.31,651.85,"41,333.02"

In [30]:
exactly_adj_am = adv_adj_am.filter(like=adv, axis=0).nlargest(10, 'LRC')
exactly_adj_am

,f,exp_f,unexp_f,unexp_abs_sqrt,dP1,LRC,G2,t,MI,odds_r_disc,N,f1,f2,l1,l2
key,,,,,,,,,,,,,,,
exactly~alike,3040,9.46,"3,030.54",55.05,0.23,8.55,"29,939.32",54.96,2.51,2.64,86330753,61599,13261,exactly,alike
exactly~opposite,498,6.71,491.29,22.17,0.05,5.94,"3,337.27",22.02,1.87,1.90,86330753,61599,9404,exactly,opposite
exactly~right,6948,145.97,"6,802.03",82.47,0.03,5.53,"41,085.55",81.60,1.68,1.74,86330753,61599,204572,exactly,right
exactly~zero,344,8.19,335.81,18.33,0.03,5.02,"1,912.07",18.11,1.62,1.64,86330753,61599,11472,exactly,zero
exactly~parallel,224,5.41,218.59,14.78,0.03,4.90,"1,238.35",14.61,1.62,1.63,86330753,61599,7577,exactly,parallel
exactly~sure,9301,602.91,"8,698.09",93.26,0.01,3.89,"34,895.53",90.19,1.19,1.26,86330753,61599,844981,exactly,sure
exactly~equal,560,33.61,526.39,22.94,0.01,3.75,"2,108.45",22.24,1.22,1.23,86330753,61599,47099,exactly,equal
exactly~conducive,214,11.71,202.29,14.22,0.01,3.68,842.32,13.83,1.26,1.27,86330753,61599,16405,exactly,conducive
exactly~correct,788,55.83,732.17,27.06,0.01,3.56,"2,723.36",26.08,1.15,1.16,86330753,61599,78240,exactly,correct
exactly~ideal,445,30.47,414.53,20.36,0.01,3.52,"1,564.21",19.65,1.16,1.17,86330753,61599,42701,exactly,ideal

In [41]:
def load_hit_table(adv_set): 
    
    # hit_df = pd.read_pickle(HITS_PATH).filter(regex=r'^[nab].*lower|text|str|head')
    # hit_df = pd.read_pickle(HITS_PATH)
    hit_df = pd.concat([pd.read_pickle(p).filter(regex=r'^[nab].*lower|text|str|head') 
           for i,p in enumerate(Path('/share/compling/data/sanpi/2_hit_tables/RBXadj/simple').iterdir()) if i < 4] )
    
    hit_df = hit_df.loc[hit_df.adv_form_lower.isin(adv_set), :]
    hit_df = hit_df.drop_duplicates()
    word_cols = hit_df.filter(regex=r'head|lower').columns
    hit_df[word_cols] = hit_df[word_cols].astype('category')
    return  hit_df
hits_df = load_hit_table(adv_set)
hits_df

,text_window,token_str,adv_form_lower,adj_form_lower,bigram_lower
hit_id,,,,,
pcc_eng_val_3.00021_x34572_05:24-25,would n't have that much of an impact,Certainly the medium could benefit from higher and more stable ' upload ' sp...,that,much,that_much
pcc_eng_val_3.00046_x34611_53:15-16,and services is only referential .,"Any use of third party trademarks , brand names , product and services is on...",only,referential,only_referential
pcc_eng_val_3.00062_x34632_31:1-2,Only thicker and creamier .,Only thicker and creamier .,only,thicker,only_thicker
pcc_eng_val_3.00076_x34651_11:35-36,trackers is not THAT good but still ...,I understand that some people really do not like to watch anything that is n...,that,good,that_good
pcc_eng_val_3.00081_x34658_05:2-3,- Immediately right of this is,"- Immediately right of this is a long , easy - angled chimney & slab , appar...",immediately,right,immediately_right
...,...,...,...,...,...
nyt_eng_19940731_0289_3:29-30,n't have been that close .,"`` I 'll probably sleep 12 hours tonight , '' she said after the U.S. beat G...",that,close,that_close
nyt_eng_19940731_0297_6:17-18,could n't be any worse than this winter,"as Paul Brazier , the Saugerties town assessor , said : `` It could n't be a...",any,worse,any_worse
nyt_eng_19940731_0298_18:8-9,"'s never been exactly crowded , but in","of course , it 's never been exactly crowded , but in the last few years the...",exactly,crowded,exactly_crowded
nyt_eng_19940731_0298_41:8-9,women who speak only Russian came in and,a couple of elderly women who speak only Russian came in and he spoke to the...,only,russian,only_russian
nyt_eng_19940731_0312_4:8-9,sexual harassment are particularly disturbing given my strong,`` Any allegations of sexual harassment are particularly disturbing given my...,particularly,disturbing,particularly_disturbing

In [42]:
hits_df.sample(3).filter(like='lower')

                              adv_form_lower adj_form_lower           bigram_lower
hit_id
apw_eng_20060507_0067_7:13-14            any         better             any_better
apw_eng_19970422_1498_10:6-7    particularly          rough     particularly_rough
apw_eng_19971224_1108_26:5-6     immediately      available  immediately_available

In [47]:
samples = {}
for i, adj in enumerate(exactly_adj_am['l2'].unique(), start=1): 
    # if i > 3: #HACK 
    #     break
    bigram = f'exactly_{adj}'
    print(f'\n({i}) {bigram}')
    samples[bigram] = sp(data=hits_df, filters=[f'bigram_lower=={bigram}'], print_sample=False, sample_size=30,
       columns=['bigram_lower', 'text_window', 'token_str'], 
       quiet=True)
    print('    > ',samples[bigram].sample(1).token_str.squeeze())
    print('    âœ“')

(1) exactly_alike
    >  Each piece is individual in characteristics , and no 2 pieces are exactly alike .
    âœ“

(2) exactly_opposite
    >  Kramnik 's opinion on the game course was exactly opposite .
    âœ“

(3) exactly_right
    >  sitting around the house , the three share increasingly strained mealtimes and watch `` The Wicker Man , '' a dizzy pagan-ritual extravaganza that 's exactly right for this crowd .
    âœ“

(4) exactly_zero
    >  infinitely small , is not exactly zero .
    âœ“

(5) exactly_parallel
    >  Orwell 's novel , `` as well as satirizing Stalinist ` purity ' and deceit ... anticipates the almost exactly parallel development of the equally drab and tyrannical ` political correctness ' of our own times . ''
    âœ“

(6) exactly_sure
    >  `` I am not exactly sure if this is the right thing to do , but it is the prudent thing ...
    âœ“

(7) exactly_equal
    >  Activase and Retavase are `` exactly equal in price , safety and efficacy , '' Yost said .
    âœ“

(8) exactly_conducive
    >  a child who might at any moment be expected to give up the toy he just got his hands on , before he gets a chance to play with it the way he wants to , is destined to be anxious and defensive , ready to fend off intruders , says Ucci -- `` not exactly conducive to sharing . ''
    âœ“

(9) exactly_correct
    >  `` So in this particular case , I think the choice was exactly correct . ''
    âœ“

(10) exactly_ideal
    >  Marler said the only mammals known to learn new sounds are whales and porpoises , and `` they 're not exactly ideal for study . ''
    âœ“

In [52]:
samples[f'exactly_{exactly_adj_am.sample(1).l2.squeeze()}'].reset_index(drop=True)

   bigram_lower                               text_window                                             token_str
0  exactly_zero  cash salary of exactly zero _ goose eggs  he took a cash salary of exactly zero _ goose eggs .
1  exactly_zero                   , is not exactly zero .              infinitely small , is not exactly zero .